//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurrentAccount()
        {
            this.From = new HashSet<Transaction>();
            this.To = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public int Balance { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<System.DateTime> AccountOpenedDate { get; set; }
        public string EmailAddress { get; set; }
        public string TokenManagerTokenKey { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> From { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> To { get; set; }
    }
}
