//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetBankDatabaseEntities : DbContext
    {
        public NetBankDatabaseEntities()
            : base("name=NetBankDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CurrentAccount> CurrentAccount { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<TokenManager> TokenManager { get; set; }
    }
}
