//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int From { get; set; }
        public int To { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Description { get; set; }
    
        public virtual CurrentAccount FromAccount { get; set; }
        public virtual CurrentAccount ToAccount { get; set; }
    }
}
